[package]
name = "async_chat_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
get_if_addrs = "0.5.3"
aes = "0.8"
cipher = "0.4.0"
hex = "0.4"
cbc = "0.1.2"
rand = "0.8"
openssl = "0.10"
eframe = "0.24.1"